name: dashfallgame
description: "A 2D Arcade Game"
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sensors_plus: ^4.0.0
  shared_preferences: ^2.2.2
  google_mobile_ads: ^5.0.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.3.10"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/sounds/

# Root level configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # Used for iOS, legacy Android, and splash fallback
  remove_alpha_ios: true
  # VVVVV THESE ARE IMPORTANT FOR ADAPTIVE ICONS & ANDROID 12+ SPLASH VVVVV
  adaptive_icon_foreground: "assets/icon/app_icon_background_removed.png" # Ensure this file exists and has padding
  adaptive_icon_background: "#007AFF" # Should match your splash color for consistency

# Root level configuration for flutter_native_splash
flutter_native_splash:
  color: "#007AFF"
  image: assets/icon/app_icon.png # This is the centered image on the splash
  # For Android 12+, the system often uses your launcher icon and the 'color' above.
  # The 'image' here might be more prominent on pre-Android 12 or if specifically configured.

  # Optional: For better Android 12+ integration, you can also specify:
  # android_12:
  #   image: assets/icon/app_icon_background_removed.png # Use the foreground for the animated icon
  #   icon_background_color: "#007AFF"
  #   image_dark: assets/icon/app_icon_background_removed.png # If you have a dark mode version
  #   icon_background_color_dark: "#007AFF" # If you have a dark mode version