// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_J4HFr6Ot53oZZDECs0s1XTqf1CQZlWk',
    appId: '1:854038169898:web:bc9103801a500e61497653',
    messagingSenderId: '854038169898',
    projectId: 'dashfall-88b7d',
    authDomain: 'dashfall-88b7d.firebaseapp.com',
    storageBucket: 'dashfall-88b7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU6fT2EBXWJz-wqODgwyYD0_YDw_fyE2Q',
    appId: '1:854038169898:android:992753d2021dbb01497653',
    messagingSenderId: '854038169898',
    projectId: 'dashfall-88b7d',
    storageBucket: 'dashfall-88b7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACgIXNy1dRSulQT06ckBD8Vcaz9xoQoNM',
    appId: '1:854038169898:ios:fb1104403dd0b8fe497653',
    messagingSenderId: '854038169898',
    projectId: 'dashfall-88b7d',
    storageBucket: 'dashfall-88b7d.firebasestorage.app',
    iosBundleId: 'com.example.dashfallgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACgIXNy1dRSulQT06ckBD8Vcaz9xoQoNM',
    appId: '1:854038169898:ios:fb1104403dd0b8fe497653',
    messagingSenderId: '854038169898',
    projectId: 'dashfall-88b7d',
    storageBucket: 'dashfall-88b7d.firebasestorage.app',
    iosBundleId: 'com.example.dashfallgame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_J4HFr6Ot53oZZDECs0s1XTqf1CQZlWk',
    appId: '1:854038169898:web:f7f15f3b135ad490497653',
    messagingSenderId: '854038169898',
    projectId: 'dashfall-88b7d',
    authDomain: 'dashfall-88b7d.firebaseapp.com',
    storageBucket: 'dashfall-88b7d.firebasestorage.app',
  );
}
